logging:
  level:
    ROOT: INFO
    org.sitmun.plugin.core: INFO
    
security:
  authentication:
    middleware:
      secret: 9ef80c644166846897f6a87d3cf6ab204d144229

# ===================================================================
# SITMUN specific properties
# ===================================================================
    
sitmun:
  config:
    url: http://localhost:8080/api/config/proxy