# Development Profile Configuration
spring:
  # H2 Console disabled for production
  h2:
    console:
      enabled: false

# Production-specific logging
logging:
  level:
    org.sitmun.mbtiles: INFO
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Production-specific actuator configuration
management:
  endpoint:
    health:
      show-details: never  # Hide detailed health info in production
  endpoints:
    web:
      exposure:
        include: health  # Minimal endpoints for production