version: '3'
services:
  proxy_1:
    build:
      context: ./proxy
      args:
        PROXY_VERSION: 0.1.0-SNAPSHOT
    ports:
      - "8081:8080"
    environment:
      sitmun.config.url: http://heroku:8080/api/config/proxy
    depends_on:
      - heroku
  proxy_2:
    build:
      context: ./proxy
      args:
        PROXY_VERSION: 0.1.0-SNAPSHOT
    ports:
      - "8082:8080"
    environment:
      sitmun.config.url: http://heroku:8080/api/config/proxy
    depends_on:
      - heroku
  heroku:
    build:
      context: ./heroku-dev-lite
      args:
        SITMUN_VERSION: 0.9.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      spring.datasource.type: com.zaxxer.hikari.HikariDataSource
      spring.datasource.url: jdbc:h2:file:./build/sitmundb
      spring.datasource.username: sample
      spring.datasource.password:
      spring.datasource.hikari.poolName: Hikari
      spring.datasource.hikari.maximum-pool-size: 1
      spring.datasource.hikari.leak-detection-threshold: 15000
      spring.datasource.hikari.connection-timeout: 500
      security.authentication.jwt.token-validity-in-miliseconds: 600000
  nginx_balancer:
    build:
      context: ./nginx
    ports:
      - "9091:80"
    depends_on:
      - proxy_1
      - proxy_2
