version: '3'
services:
  admin:
    image: sitmun/proxy-middleware
    build:
      context: ./proxy
      args:
        PROXY_VERSION: 0.1.0-SNAPSHOT
    environment:
      sitmun.config.url: backend:8081/api/config/proxy
    ports:
      - "9090:8080"
    depends_on:
      - backend
  backend:
    image: heroku-dev-full:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: heroku,openapi-provided
      LOGGING_LEVEL_ROOT: INFO
      JAVA_OPTS: -Xmx512m -Xms512m
      spring.datasource.url: jdbc:postgresql://postgres:5432/stm3
      spring.datasource.username: stm3
      spring.datasource.password: stm3
      spring.datasource.hikari.auto-commit: false
      spring.liquibase.run-async: true
      server.forward-headers-strategy: framework
      security.authentication.jwt.secret: 9ef80c644166846897f6a87d3cf6ab204d144229
      TZ: CET
    depends_on:
      - postgres
  postgres:
    image: postgres:14.7-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: stm3
      POSTGRES_USER: stm3
    volumes:
      - ./postgres/scripts/:/docker-entrypoint-initdb.d
