version: '3'
services:
  backend:
    build:
      context: ./docker-nginx-balanced/heroku-dev-lite
      args:
        SITMUN_VERSION: 0.9.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      spring.datasource.type: com.zaxxer.hikari.HikariDataSource
      spring.datasource.url: jdbc:h2:file:./build/sitmundb
      spring.datasource.username: sample
      spring.datasource.password:
      spring.datasource.hikari.poolName: Hikari
      spring.datasource.hikari.maximum-pool-size: 1
      spring.datasource.hikari.leak-detection-threshold: 15000
      spring.datasource.hikari.connection-timeout: 500
      security.authentication.jwt.token-validity-in-miliseconds: 600000
